apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devx-beta
  description: An example of a Backstage application.
  annotations:
    kafka-topology/contracts-path: packages/kafka-topology/public/contracts
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
